### ISSUE TITLE
屏幕适配

### ISSUE THREAD

**Issue by wswmsword** [libwiki/vue3-vant-template#1]
libwiki 你好，最近我开发了个屏幕适配插件，[postcss-mobile-forever](https://github.com/wswmsword/postcss-mobile-forever)，欢迎试用～

这个插件可以让移动端视图在全平台展示，他可以限制 vw 的最大值，相当于 rem 单位设置最大 font-size，插件也可以生成桌面端和横屏的媒体查询，这样在不同的屏幕上能展示合适的视图。另外插件支持传入 viewportWidth 函数，支持动态生成视图宽度，这样方便引入外部库。

感兴趣可以关注一下，我持续维护，及时修复～

**Comment by libwiki** [comment]
目前的rem适配暂时替换为postcss-px-to-viewport，后续有时间会尝试使用[postcss-mobile-forever](https://github.com/wswmsword/postcss-mobile-forever)

**Comment by wswmsword** [comment]
[postcss-mobile-forever](https://github.com/wswmsword/postcss-mobile-forever) 支持 px-to-viewport 大部分功能，相关功能都通过了单元测试。这个库的目的是解决 px-to-viewport 适配视口单位但是不考虑大屏，没有限制最大宽度的问题。

**Comment by wswmsword** [comment]
> 目前的rem适配暂时替换为postcss-px-to-viewport，后续有时间会尝试使用[postcss-mobile-forever](https://github.com/wswmsword/postcss-mobile-forever)

欢迎尝试😄
